### ISSUE TITLE
Broken pipe after voice command

### ISSUE THREAD

**Issue by amahlaka** [davidmroth/AlexaPi#3] opened 2016-11-24 19:36 UTC
```
 ERROR - error: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/opt/AlexaPi/src/alexa/http/http.py", line 191, in post
    request = self.__session.post(full_url, headers=headers, files=payload, stream=True, timeout=None)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hyper/contrib.py", line 78, in send
    request.headers
  File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 103, in request
    method=method, url=url, body=body, headers=headers
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 183, in request
    self._send_headers(method, url, headers)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 228, in _send_headers
    self._sock.send(b' '.join([method, url, b'HTTP/1.1\r\n']))
  File "/usr/lib/python2.7/ssl.py", line 667, in send
    v = self._sslobj.write(data)
error: [Errno 32] Broken pipe
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/AlexaPi/src/alexa/avs/directive_dispatcher.py", line 76, in processor
    log.debug("{}(process_response Error){} Status Code: {} - {}".format(shared.bcolors.WARNING, shared.bcolors.ENDC, r.status_code, r.text))
AttributeError: 'bool' object has no attribute 'status_code'

```

**Comment by davidmroth** [comment] 2016-11-24 19:49
> error: [Errno 32] Broken pipe

Based on the other errors you are getting, this error is most likely the result of a malformed url, which is probably the result of a missing config. See my the config I posted in #1 and the debugging request in issue #2.

I have also added some updates to my latest branch would should help make the initial setup process a little less painful.

**Comment by davidmroth** [comment] 2016-11-25 01:19
Closing as this is a duplicate of #1

**Closed as completed by davidmroth** 2016-11-25 01:19 UTC
